
[fixes]

	[fixes.allow_void_trading]
		enabled = false

	[fixes.allow_unsafe_teleportation]
		#If you want to use sand duping,please turn on this
		enabled = false

	[fixes.allow_sand_duping]
		enabled = false

	[fixes.allow_update_incorrect_trip_wire]
		enabled = false

	[fixes.folia]

		[fixes.folia.fix_spector_teleportation]
			enabled = true

		[fixes.folia.fix_high_velocity_issue]
			enabled = true
			warn_on_detected = true

		[fixes.folia.prevent_teleportasync_call_during_moving]
			enabled = false
			throw_on_detected = true

	[fixes.use_vanilla_random_source]
		enable_for_player_entity = false

[optimizations]

	[optimizations.load_chunks_to_active_climbing_entities]
		allow = false

	#Optimizes entity brains when
	#they're far away from the player
	[optimizations.dab]
		#This value defines how often in ticks, the furthest entity
		#will get their pathfinders and behaviors ticked. 20 = 1s
		max-tick-freq = 20
		#This value defines how much distance modifies an entity's
		#tick frequency. freq = (distanceToPlayer^2) / (2^value)
		#If you want further away entities to tick less often, use 7.
		#If you want further away entities to tick more often, try 9.
		activation-dist-mod = 0
		#This value determines how far away an entity has to be
		# from the player to start being effected by DEAR.
		start_distance = 12
		blacklisted-entities = []
		enabled = true

	[optimizations.skip_goal_selector_tick_in_inactive_tick]
		enabled = true

	[optimizations.alternative_keepalive_handling]
		enabled = true

	[optimizations.async_path_processing]
		max_threads = 0
		enabled = true
		keep_alive_time = 60

	[optimizations.variable_entity_waking_up]
		entity_wakeup_duration_ratio_standard_deviation = 0.2

	[optimizations.projectile]
		max-loads-per-projectile = 0
		max-loads-per-tick = 0

	[optimizations.reduce_sensor_work]
		delay_ticks = 10
		enabled = true

	[optimizations.suffocation_optimization]
		enabled = true

	#These values define a entity's maximum lifespan. If an
	#entity is in this list and it has survived for longer than
	#that number of ticks, then it will be removed. Setting a value to
	#-1 disables this feature.
	[optimizations.entity_timeouts]
		MOOSHROOM = -1
		MAGMA_CUBE = -1
		SILVERFISH = -1
		MULE = -1
		HOGLIN = -1
		LEASH_KNOT = -1
		HUSK = -1
		VINDICATOR = -1
		WARDEN = -1
		HOPPER_MINECART = -1
		PILLAGER = -1
		SHULKER_BULLET = -1
		VILLAGER = -1
		AREA_EFFECT_CLOUD = -1
		PAINTING = -1
		TURTLE = -1
		TRADER_LLAMA = -1
		SMALL_FIREBALL = -1
		TNT = -1
		CAVE_SPIDER = -1
		SLIME = -1
		DROWNED = -1
		FIREBALL = -1
		EVOKER = -1
		MARKER = -1
		EXPERIENCE_BOTTLE = -1
		ENDERMITE = -1
		AXOLOTL = -1
		COMMAND_BLOCK_MINECART = -1
		PLAYER = -1
		ITEM = -1
		TEXT_DISPLAY = -1
		SALMON = -1
		ZOMBIE = -1
		GOAT = -1
		STRIDER = -1
		PANDA = -1
		OCELOT = -1
		ENDERMAN = -1
		CHEST_MINECART = -1
		ZOMBIE_VILLAGER = -1
		LLAMA = -1
		ENDER_DRAGON = -1
		WITCH = -1
		EXPERIENCE_ORB = -1
		ITEM_FRAME = -1
		WITHER = -1
		ARROW = -1
		CREEPER = -1
		ILLUSIONER = -1
		BREEZE = -1
		CAMEL = -1
		COD = -1
		ZOMBIE_HORSE = -1
		FURNACE_MINECART = -1
		RAVAGER = -1
		BOAT = -1
		SHULKER = -1
		SNIFFER = -1
		BEE = -1
		ITEM_DISPLAY = -1
		PHANTOM = -1
		BLAZE = -1
		SKELETON_HORSE = -1
		COW = -1
		WANDERING_TRADER = -1
		END_CRYSTAL = -1
		PIG = -1
		ZOGLIN = -1
		WOLF = -1
		IRON_GOLEM = -1
		FROG = -1
		SHEEP = -1
		VEX = -1
		ENDER_PEARL = -1
		BLOCK_DISPLAY = -1
		TRIDENT = -1
		PIGLIN_BRUTE = -1
		POLAR_BEAR = -1
		MINECART = -1
		LIGHTNING_BOLT = -1
		POTION = -1
		FISHING_BOBBER = -1
		CHEST_BOAT = -1
		SQUID = -1
		DRAGON_FIREBALL = -1
		ELDER_GUARDIAN = -1
		HORSE = -1
		TNT_MINECART = -1
		ARMOR_STAND = -1
		PARROT = -1
		EVOKER_FANGS = -1
		FOX = -1
		GIANT = -1
		STRAY = -1
		SPECTRAL_ARROW = -1
		CAT = -1
		RABBIT = -1
		DONKEY = -1
		EYE_OF_ENDER = -1
		SPAWNER_MINECART = -1
		GLOW_ITEM_FRAME = -1
		INTERACTION = -1
		TROPICAL_FISH = -1
		ALLAY = -1
		SPIDER = -1
		SKELETON = -1
		WITHER_SKELETON = -1
		CHICKEN = -1
		ZOMBIFIED_PIGLIN = -1
		SNOWBALL = -1
		GLOW_SQUID = -1
		SNOW_GOLEM = -1
		WITHER_SKULL = -1
		PUFFERFISH = -1
		GUARDIAN = -1
		EGG = -1
		LLAMA_SPIT = -1
		WIND_CHARGE = -1
		FALLING_BLOCK = -1
		PIGLIN = -1
		GHAST = -1
		BAT = -1
		DOLPHIN = -1
		TADPOLE = -1
		FIREWORK_ROCKET = -1

[misc]

	[misc.warn_on_offline_mode]
		enabled = false

	[misc.server_mod_name]
		name = "Luminol"
		vanilla_spoof = false

	[misc.watchdog]
		warn_period_ticks = 100
		timeout_ticks = 600
		enabled = false

	[misc.mojang_chat_sign]
		enabled = false

	[misc.username_checks]
		enabled = true

	[misc.io_uring_support]
		enabled = true

	[misc.mojang_out_of_order_chat_check]
		enabled = false

	[misc.region_format]
		linear_compression_level = 1
		linear_flush_frequency = 10
		formatName = "ANVIL"
		linear_flusher_thread_count = 1

	[misc.tpsbar]
		ping_color_list = ["GREEN", "YELLOW", "RED", "PURPLE"]
		format = "<gray>TPS<yellow>:</yellow> <tps> MSPT<yellow>:</yellow> <mspt> Ping<yellow>:</yellow> <ping>ms"
		tps_color_list = ["GREEN", "YELLOW", "RED", "PURPLE"]
		enabled = false
		update_interval_ticks = 15

[gameplay]

	[gameplay.leaves_bladeren_protocol]
		enable_mspt_sync_protocol = false
		enable_base_protocol = false
		mspt_sync_interval = 20

	[gameplay.leaves_carpet_protocol]
		enabled = false

